career:
  birthday: 09-12-1999
  programming-start-date: 01-07-2018
  professional-career-start-date: 01-09-2021
  certificates:
    - title: Level 2 Certificate in ESOL International (Advanced)
      institution: Cambridge University Press & Assessment English
      acquisitionDate: 01-06-2016

    - title: M18 English A Language and Literature Higher Level
      institution: International Baccalaureate
      acquisitionDate: 01-07-2018

    - title: Bilingual VWO - Atheneum
      institution: Tabor College Werenfridus
      acquisitionDate: 02-07-2018

    - title: BSc Computer Science (7,7 GPA)
      institution: Vrije Universiteit Amsterdam
      acquisitionDate: 01-08-2021

    - title: Train De Trainer
      institution: ICM
      acquisitionDate: 01-07-2023
  skills:
    - name: Java
      proficiency: 9

    - name: Kubernetes
      proficiency: 7

    - name: AKS
      proficiency: 6

    - name: Spring Boot
      proficiency: 8

    - name: Coaching
      proficiency: 7

    - name: Clean Code & Architecture
      proficiency: 7

    - name: Github Actions
      proficiency: 4

    - name: Python
      proficiency: 6

    - name: Bootstrap & Thymeleaf
      proficiency: 6

  events:
    - employer: DEEN Distribution Centre
      job-title: Storage employee
      description: cx
      start: 01-01-2015
      end: 01-06-2015
      icon:
        classes: fa-solid fa-flag-checkered fa-beat
        style: "color: #149f2b;"

    - employer: McDonald’s
      job-title: Crew member
      description: cx
      start: 01-06-2015
      end: 01-01-2016
      icon:
        classes: fas fa-regular fa-burger fa-bounce
        style: "color: #e18709;"




