career:
  birthday: 09-12-1999
  programming-start-date: 01-07-2018
  professional-career-start-date: 01-09-2021
  certificates:
    - title: Level 2 Certificate in ESOL International (Advanced)
      institution: Cambridge University Press & Assessment English
      acquisitionDate: 01-06-2016

    - title: M18 English A Language and Literature Higher Level
      institution: International Baccalaureate
      acquisitionDate: 01-07-2018

    - title: Bilingual VWO - Atheneum
      institution: Tabor College Werenfridus
      acquisitionDate: 02-07-2018

    - title: BSc Computer Science (7,7 GPA)
      institution: Vrije Universiteit Amsterdam
      acquisitionDate: 01-08-2021

    - title: Train De Trainer
      institution: ICM
      acquisitionDate: 01-07-2023
  skills:
    - name: Java
      proficiency: 9

    - name: Kubernetes
      proficiency: 7

    - name: AKS
      proficiency: 6

    - name: Spring Boot
      proficiency: 8

    - name: Coaching
      proficiency: 7

    - name: Clean Code & Architecture
      proficiency: 7

    - name: Github Actions
      proficiency: 4

    - name: Python
      proficiency: 6

    - name: Bootstrap & Thymeleaf
      proficiency: 6

  events:
    - employer: DEEN Distribution Centre
      job-title: Storage employee
      description: Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
      start: 01-01-2015
      end: 01-06-2015
      icon:
        classes: fa-solid fa-flag-checkered fa-beat
        style: "color: #149f2b;"

    - employer: McDonald’s
      job-title: Crew member
      description: cx
      start: 01-06-2015
      end: 01-01-2016
      icon:
        classes: fas fa-regular fa-burger fa-bounce
        style: "color: #e18709;"

    - employer: Lunchroom Cafetaria Celine
      job-title: All-around employee
      description: Worked very hard under a strict owner to become disciplined, efficient and handy as a person with a good work ethic.
      start: 01-01-2016
      end: 01-01-2020
      icon:
        classes: fa-solid fa-utensils style
        style: "color: #5f7395;"

    - employer: MedIT Solutions B.V.
      job-title: Junior Software Engineer
      description: Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
      start: 01-09-2021
      end: 01-07-2022
      icon:
        classes: fa-solid fa-laptop
        style: "color: #0cac59;"

    - employer: Ordina
      job-title: Medior Software Engineer
      description: Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
      start: 01-07-2022
      end:
      icon:
        classes: fa-solid fa-laptop-code
        style: "color: #cc0f5b;"

    - employer: Rabobank
      job-title: Medior Software Engineer
      description: Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
      start: 01-09-2022
      end:
      icon:
        classes: fa-solid fa-piggy-bank fa-shake
        style: "color: #e49bd0;"
  hobbies:
    - name: Programming
      icon:
        classes: fa-solid fa-laptop-code
        style: "color: #1ad5c0;"

    - name: Food
      icon:
        classes: fa-solid fa-utensils fa-bounce
        style:

    - name: Chess
      icon:
        classes: fa-solid fa-chess-board fa-xl
        style:

    - name: Gaming
      icon:
        classes: fa-solid fa-gamepad fa-shake
        style: "color: #c93c0d;"

    - name: Cooking
      icon:
        classes: fa-solid fa-kitchen-set
        style: "color: #636fab"

    - name: Anime
      icon:
        classes: fa-solid fa-eye
        style: "color: #0b53d0;"



