career:
  birthday:
    day-of-month: 09
    month: 12
    year: 1999
  programming-start-date:
    day-of-month: 1
    month: 7
    year: 2018
  professional-career-start-date:
    day-of-month: 1
    month: 09
    year: 2021
  certificates:
    - title: Level 2 Certificate in ESOL International (Advanced)
      institution: Cambridge University Press & Assessment English
      acquisitionDate:
        day-of-month: 1
        month: 6
        year: 2016

    - title: M18 English A Language and Literature Higher Level
      institution: International Baccalaureate
      acquisitionDate:
        day-of-month: 1
        month: 7
        year: 2018

    - title: Bilingual VWO - Atheneum
      institution: Tabor College Werenfridus
      acquisitionDate:
        day-of-month: 2
        month: 7
        year: 2018

    - title: BSc Computer Science (7,7 GPA)
      institution: Vrije Universiteit Amsterdam
      acquisitionDate:
        day-of-month: 1
        month: 08
        year: 2021

    - title: Train De Trainer
      institution: ICM
      acquisitionDate:
        day-of-month: 1
        month: 7
        year: 2023
  skills:
    - name: Java
      proficiency: 9
    - name: Kubernetes
      proficiency: 7
    - name: AKS
      proficiency: 6
    - name: Spring Boot
      proficiency: 8
    - name: Coaching
      proficiency: 7
    - name: Clean Code & Architecture
      proficiency: 7
    - name: Github Actions
      proficiency: 4
    - name: Python
      proficiency: 6
    - name: Bootstrap & Thymeleaf
      proficiency: 6
  events:
    - title: Deen Distributie
      description: some
      icon-html-class: fa-fa somethin
      start:
        day-of-month: 2
        month: 12
        year: 2002
      end:
        day-of-month: 3
        month: 12
        year: 2002



