career:
  birthday: 09-12-1999
  programming-start-date: 01-07-2018
  professional-career-start-date: 01-09-2020
  certificates:
    - title: Level 2 Certificate in ESOL International (Advanced)
      institution: Cambridge University Press & Assessment English
      acquisitionDate: 01-06-2016

    - title: M18 English A Language and Literature Higher Level
      institution: International Baccalaureate
      acquisitionDate: 01-07-2018

    - title: Bilingual VWO - Atheneum
      institution: Tabor College Werenfridus
      acquisitionDate: 02-07-2018

    - title: BSc Computer Science (7,7 GPA)
      institution: Vrije Universiteit Amsterdam
      acquisitionDate: 01-08-2021

    - title: Train De Trainer
      institution: ICM
      acquisitionDate: 01-07-2023

  hobbies:
    - name: Programming
      icon:
        classes: fa-solid fa-laptop-code
        style: "color: #1ad5c0;"

    - name: Food
      icon:
        classes: fa-solid fa-utensils fa-bounce
        style:

    - name: Chess
      icon:
        classes: fa-solid fa-chess-board fa-xl
        style:

    - name: Gaming
      icon:
        classes: fa-solid fa-gamepad fa-shake
        style: "color: #c93c0d;"

    - name: Cooking
      icon:
        classes: fa-solid fa-kitchen-set
        style: "color: #636fab"

    - name: Anime
      icon:
        classes: fa-solid fa-user-secret
        style:

  skills:
    - name: Java
      proficiency: 9

    - name: Kotlin
      proficiency: 9
      
    - name: Microservice architecture
      proficiency: 7

    - name: Agile/Scrum
      proficiency: 7

    - name: Kubernetes
      proficiency: 7

    - name: AKS
      proficiency: 6

    - name: OAuth2
      proficiency: 7

    - name: Spring Boot
      proficiency: 8

    - name: Coaching
      proficiency: 7

    - name: Clean Code & Architecture
      proficiency: 7

    - name: Github Actions
      proficiency: 6

    - name: Python
      proficiency: 6

    - name: Bootstrap 5 & Thymeleaf
      proficiency: 6

  events:
    - employer: DEEN Distribution Centre
      job-title: Storage employee
      description:
        I kicked off my career as an Order Picker at DEEN Distribution Centre. It wasn't all boxes and shelves;
        though that was most of the work.
      start: 01-01-2015
      end: 01-06-2015
      icon:
        classes: fa-solid fa-flag-checkered fa-beat
        style: "color: #149f2b;"

    - employer: McDonald’s
      job-title: Crew member
      description:
        I started my Horeca journey under the golden arches at McDonald's — a crash course in fast-paced service,
        teamwork, and the sizzling art of flipping burgers.
      start: 01-06-2015
      end: 01-01-2016
      icon:
        classes: fas fa-regular fa-burger fa-bounce
        style: "color: #e18709;"

    - employer: Lunchroom Cafetaria Celine
      job-title: All-around employee
      description: I worked very hard under a strict owner to become disciplined, efficient and handy as a person with
        a good work ethic. Turns out, navigating the Horeca world was a whole different ballgame compared to my
        McDonald's days. It added layers to my experience, revealing the challenges and flavors of
        the hospitality industry
      start: 01-01-2016
      end: 01-01-2020
      icon:
        classes: fa-solid fa-utensils style
        style: "color: #5f7395;"

    - employer: MedIT Solutions B.V.
      job-title: Junior Software Engineer
      description: Stepping into the world of software engineering at a small pharmaceutical company felt like entering
        a new dimension. Armed with my CS degree, I dove into Java Spring and Scrum methodologies,
        discovering a whole realm of real-world application that academia only hinted at. It was a hands-on initiation
        that brought my coding skills to life. I cherish the memories of our extended daily standups, brimming with
        laughter and jokes, to the point where it hardly felt like I was even at work.
      start: 01-09-2020
      end: 01-07-2022
      icon:
        classes: fa-solid fa-laptop
        style: "color: #0cac59;"

    - employer: Ordina
      job-title: Medior Software Engineer
      description: In my previous role as a software engineer in secondment, I've found a dynamic and ever-evolving
        environment. This experience continues to be a journey of growth, exposing me to diverse projects and challenges that keep me engaged and motivated
        this experience as a consultant surely will contribute to my journey as an engineer.
      start: 01-07-2022
      end: 01-04-2024
      icon:
        classes: fa-solid fa-laptop-code
        style: "color: #cc0f5b;"

    - employer: Rabobank
      job-title: Medior Software Engineer
      description: In my  previous role at Rabobank, my journey unfolds as a software engineer, expanding my skills in
        Scrum and delving deep into Java development and devops. The cutting-edge microservices environment introduces
        me to Kubernetes and Azure, providing a rich landscape for honing my expertise in modern software engineering.
      start: 01-09-2022
      end: 01-04-2024
      icon:
        classes: fa-solid fa-piggy-bank fa-shake
        style: "color: #e49bd0;"

    - employer: Qualogy
      job-title: Medior Software Engineer
      description: My consultancy career continues as I love my current role as Medior Java Software Engineer at Qualogy. 
        I'm excited for the amazing assignments Qualogy has in store for me!
      start: 01-04-2024
      end:
      icon:
        classes: fa-solid fa-q
        style: "color: #b91d1d;"

    - employer: Ahold Delhaize
      job-title: Software Engineer
      description: In my role as the sole Kotlin developer on a cross-functional team of Salesforce admins and developers,
        I revamped legacy Kotlin microservices into robust, compliant services using in-house frameworks.
        I enforced event-driven Kafka protocols, regularly represented my team in architecture sessions, and introduced clean code,
        architecture principles, pair programming, and quality gate practices.
        I led knowledge-sharing initiatives, organized cross-team sessions, and drove our backlog with improvement and roadmap tasks.
        My work utilized Kotlin, Spring Boot, Kubernetes, ArgoCD, Kafka, and other key technologies.
      start: 01-08-2024
      end:
      icon:
        classes: "fa-duotone fa-solid fa-cart-shopping"
        style:

