apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: portfolio-ingress
  namespace: portfolio
spec:
  ingressClassName: nginx
  rules:
    - host: phitiet.nl
      http:
        paths:
          - pathType: Prefix
            backend:
              service:
                name: portfolio-service
                port:
                  number: 8080
            path: /