name: deploy_main_to_raspberry
on:
  push:
    branches:
      - main
  workflow_dispatch: { }
jobs:
  build:
    timeout-minutes: 3
    runs-on: ubuntu-latest
    steps:
      - name: checkout_code
        uses: actions/checkout@v4
      - name: setup_java_21
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '21'

      - name: setup_docker_buildx
        uses: docker/setup-buildx-action@v3

      - name: build_with_maven
        run: mvn clean package

      - name: login_to_docker
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{github.repository_owner}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: build_and_push
        uses: docker/build-push-action@v4
        with:
          push: true
          context: .
          platforms: linux/arm64
          tags: ghcr.io/phitiet/portfolio:latest
